### ISSUE TITLE
Remove media_entity_browser dependency

### ISSUE THREAD

**Issue by webflo** [BurdaMagazinOrg/module-dcx-integration#33]
dcx_entity_browser has a dependency on media_entity_browser. media_entity_browser has been removed in the last thunder beta. I think we should remove it as well and switch plain entity_browser instead.

I could not find any code or config that requires media_entity_browser. 

// ping @chrfritsch

**Comment by chrfritsch** [comment]
Thats right, we should remove it.

**Comment by chrfritsch** [comment]
Done

**Comment by webflo** [comment]
Thx
