### ISSUE TITLE
Module is incompatible with Drupal 8.2

### ISSUE THREAD

**Issue by webflo** [BurdaMagazinOrg/module-dcx-integration#36]
I create the 8.x-2.x branch to fix the incompatibility https://github.com/webflo/module-dcx-integration/tree/8.x-2.x

Requires 8.2.x-dev because of the regression in rc1. see https://www.drupal.org/node/2796953 for  further information.

**Comment by chrfritsch** [comment]
I have opened a 8.x-2.x branch and overtook your changes inside
