### ISSUE TITLE
DCX image import: Fatal PHP Error when migrate_drupal module is enabled

### ISSUE THREAD

**Issue by IT-Cru** [BurdaMagazinOrg/module-dcx-integration#43]
Auf der Website ist ein unvorhergesehener Fehler aufgetreten. Bitte versuchen Sie es später nochmal.

Drupal\Core\Database\ConnectionNotDefinedException: The specified database connection is not defined: migrate in Drupal\Core\Database\Database::openConnection() (line 361 of core/lib/Drupal/Core/Database/Database.php).
Drupal\Core\Database\Database::getConnection('default', 'migrate') (Line: 130)
Drupal\migrate\Plugin\migrate\source\SqlBase->setUpDatabase(Array) (Line: 93)
Drupal\migrate\Plugin\migrate\source\SqlBase->getDatabase() (Line: 138)
Drupal\migrate\Plugin\migrate\source\SqlBase->select('node_type', 't') (Line: 36)
Drupal\node\Plugin\migrate\source\d7\NodeType->query() (Line: 148)
Drupal\migrate\Plugin\migrate\source\SqlBase->prepareQuery() (Line: 163)
Drupal\migrate\Plugin\migrate\source\SqlBase->initializeIterator() (Line: 65)
Drupal\node\Plugin\migrate\source\d7\NodeType->initializeIterator() (Line: 244)
Drupal\migrate\Plugin\migrate\source\SourcePluginBase->getIterator() (Line: 286)
Drupal\migrate\Plugin\migrate\source\SourcePluginBase->rewind() (Line: 87)
Drupal\node\Plugin\migrate\D7NodeDeriver->getDerivativeDefinitions(Array) (Line: 100)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDerivatives(Array) (Line: 86)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions() (Line: 251)
Drupal\migrate\Plugin\MigrationPluginManager->findDefinitions() (Line: 175)
Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() (Line: 150)
Drupal\migrate\Plugin\MigrationPluginManager->expandPluginIds(Array) (Line: 103)
Drupal\migrate\Plugin\MigrationPluginManager->createInstances(Array, Array) (Line: 89)
Drupal\migrate\Plugin\MigrationPluginManager->createInstance('dcx_migration') (Line: 62)
Drupal\dcx_migration\DcxImportService->getMigrationExecutable() (Line: 77)
Drupal\dcx_migration\DcxImportService->import(Array) (Line: 76)
Drupal\dcx_migration\Form\DcxImportForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 51)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 585)
Drupal\Core\Form\FormBuilder->processForm('dcx_import_form', Array, Object) (Line: 314)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 74)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by chrfritsch** [comment]
migrate_drupal is not a dependency of the dcx module. So it seems like this is not a dcx problem.

If you want to use migrate_drupal for other use-cases you have to specify the database connection. migrate_drupal requires this
